### PR TITLE
Rename project

### PR DESCRIPTION
**Pull request by DamienCassou**
Fix issue #23

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
maybe just one commit is needed, or?

**Comment by BenjaminVanRyseghem** [comment]
squash the commits, and when green, you have my 🍏 🚥  😛

**Comment by DamienCassou** [comment]
I don't think travis is going to do anything anytime soon. I propose to merge the PR as is (gulp runs fine locally).

**Comment by DamienCassou** [comment]
Apparently, travis passed: https://travis-ci.org/foretagsplatsen/klassified/builds/162703181

**Comment by DamienCassou** [comment]
I force merge because it seems github is not notified by travis.

**Pull request merged**
