### PR TITLE
Optimize supercall installation

### PR DESCRIPTION
**Pull request by NicolasPetton**
* Do not perform supercall installation on both my and that unless methods in
  both objects need it.
* Optimize `installSuper` itself with a for loop.

---
This change is [Reviewable](https://reviewable.io/reviews/foretagsplatsen/klassified/46)

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
THIS IS NOT BUILDING!!!

**Comment by NicolasPetton** [comment]
It builds, but the minified version of widgetjs has issues with it. I'll investigate.

**Comment by NicolasPetton** [comment]
I fixed the issue with widgetjs, all tests are green in klassified, monitor, and widgetjs. I say we go for this.

**Comment by NicolasPetton** [comment]
Before:

screenshot from 2017-04-27 10-15-04

After:

screenshot from 2017-04-27 10-15-11

**Comment by DamienCassou** [comment]
Awesome

**Comment by DamienCassou** [comment]
I can reproduce the speed increase on monitor tests. Amazing job @NicolasPetton! I rebuilt the dist/ files with the same almond we previously used (you used a slightly older version) so the diff of the PR is cleaner.

**Pull request merged**
